language: node_js
sudo: false
node_js:
- 16
install:
- npm i
script: true
before_deploy:
  - npm install -g auto-dist-tag@1
  - auto-dist-tag --write
deploy:
  provider: npm
  email: gautaz@users.noreply.github.com
  on:
    tags: true
    repo: r2d2bzh/js-backend-rules
  skip_cleanup: 'true'
  api_key:
    secure: EiScivkiX0vHPemlpakws2ScUdcxauxFwN1vp/adG4PoODkrQ1opJ5OYHaYJ8qLpGcTFgJlL+YdnhWR+1UOjH421fGXIAPOPTn6eba0dlH53FJeY/LMK1IiQ0ymnKt7SsKp/CZxbcMxy7oIQO1tYKtpGF/CsSzkSIykGIpRC8UGuhKP+UqSSEGdFQFBKjxzt6VNEmk2mmyIgb78cb241EWkJgtHhdmDklhONdpQXbvOLv+xclJcoSLubE+kGEe09nfL9bMKrGYlo8oYISQ7GJCV1/4xBbLitg8mKLVHLbClD2NuaqBKv7ebVz3zKbKvIWtpUdYZQ/t0flYxt/box1IFn/5x7LBVdmo09u2TEqRJivaQr/LHnYbyyvv590rnaXLlixZU8dyPfqkjWP4weGu+5aY9BwrVH1RoQMmjFTLBBz2NAqHlSC0ffcVib0kASZfxb7xjhHAYsU44YHu1l2X0eVC69Ixdkn32BcA3wE31AqzQBRZcTjdb7Yq/nn3gj++5PNC9TErqltsaVMy28StDY1IOXfVp0nbty1qi/8DKx0WQgMp/ctQ4SdCVR0PYYrMSpo8wrbTNI+f5WBK0CnSx1ZolOqAS8SakUPX3Sipa2DxTsrMT6rwLhrgQzRXuK4EACNCsgbdoegqZhvs6hIQvVzLFNTvrVIqsZ1UDg/t8=
