// DO NOT EDIT THIS FILE AS IT IS GENERATED BY @r2d2bzh/js-rules
import { defineConfig } from 'eslint/config';
import r2d2bzhEslintConfig from '@r2d2bzh/eslint-config';

export default defineConfig([
  {
    extends: [r2d2bzhEslintConfig],
  },
]);
