import { join as path } from 'node:path';
import { addHashedHeader, toYAML } from '@r2d2bzh/js-rules';

export default (options) => (config) => ({
  ...config,
  [path('helm', 'Chart.yaml')]: helmChart(options),
});

const helmChart = ({ helmChart, scaffolderName, name, version, description }) => {
  const scaffold = {
    apiVersion: 'v1',
    name,
    version,
    description,
    appVersion: version,
  };
  return {
    configuration: {
      ...helmChart,
      ...scaffold,
    },
    formatters: [
      toYAML,
      addHashedHeader([
        `THIS FILE IS PARTIALLY GENERATED BY ${scaffolderName}`,
        `The following fields are generated: ${Object.keys(scaffold).join(', ')}`,
      ]),
    ],
  };
};
